name: ACCELQ CI Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ACCELQ Github-A Connect
        uses: accelQ-Inc/accelq-ci-github-actions@v1.4
        with:
          # Your ACCELQ Application URL (no trailing slashes)
          appURL: 'https://training.accelq.io'

          # Your ACCELQ User ID
          userName: 'keerthi.shivani@accelq.com'

          # API key (store this in GitHub Secrets for security)
          apikey: Bmm19-qeCCfZNArr2mH1QH1YwGBYGyaUZB-0w6nOkNg

          # Tenant Code from your ACCELQ Profile page
          tenantCode: 'accelqtraining'

          # Job ID from your CI Job in ACCELQ
          jobId: '92452'

          # Optional parameters (you can leave them empty)
          runParam: ''
          proxyHost: ''
          proxyPort: ''
          stepFailureThreshold: ''
          maxWaitTimeInMins: ''

      - name: Post-run confirmation
        run: echo "ACCELQ CI Job triggered successfully!"
